export const COUNTRIES = [
    {abbr: 'AD', name: 'Andorra'},
    {abbr: 'AE', name: 'United Arab Emirates'},
    {abbr: 'AF', name: 'Afghanistan'},
    {abbr: 'AG', name: 'Antigua & Barbuda'},
    {abbr: 'AI', name: 'Anguilla'},
    {abbr: 'AL', name: 'Albania'},
    {abbr: 'AM', name: 'Armenia'},
    {abbr: 'AN', name: 'Netherlands Antilles'},
    {abbr: 'AO', name: 'Angola'},
    {abbr: 'AR', name: 'Argentina'},
    {abbr: 'AT', name: 'Austria'},
    {abbr: 'AU', name: 'Australia'},
    {abbr: 'AW', name: 'Aruba'},
    {abbr: 'AX', name: 'Åland Islands'},
    {abbr: 'AZ', name: 'Azerbaijan'},
    {abbr: 'BA', name: 'Bosnia & Herzegovina'},
    {abbr: 'BB', name: 'Barbados'},
    {abbr: 'BD', name: 'Bangladesh'},
    {abbr: 'BE', name: 'Belgium'},
    {abbr: 'BF', name: 'Burkina Faso'},
    {abbr: 'BG', name: 'Bulgaria'},
    {abbr: 'BH', name: 'Bahrain'},
    {abbr: 'BI', name: 'Burundi'},
    {abbr: 'BJ', name: 'Benin'},
    {abbr: 'BL', name: 'St Barthélemy'},
    {abbr: 'BM', name: 'Bermuda'},
    {abbr: 'BN', name: 'Brunei'},
    {abbr: 'BO', name: 'Bolivia'},
    {abbr: 'BQ', name: 'Caribbean Netherlands'},
    {abbr: 'BR', name: 'Brazil'},
    {abbr: 'BS', name: 'Bahamas'},
    {abbr: 'BT', name: 'Bhutan'},
    {abbr: 'BV', name: 'Bouvet Island'},
    {abbr: 'BW', name: 'Botswana'},
    {abbr: 'BY', name: 'Belarus'},
    {abbr: 'BZ', name: 'Belize'},
    {abbr: 'CA', name: 'Canada'},
    {abbr: 'CC', name: 'Cocos (Keeling) Islands'},
    {abbr: 'CD', name: 'Congo - Kinshasa'},
    {abbr: 'CF', name: 'Central African Republic'},
    {abbr: 'CG', name: 'Congo - Brazzaville'},
    {abbr: 'CH', name: 'Switzerland'},
    {abbr: 'CI', name: 'Côte d’Ivoire'},
    {abbr: 'CK', name: 'Cook Islands'},
    {abbr: 'CL', name: 'Chile'},
    {abbr: 'CM', name: 'Cameroon'},
    {abbr: 'CN', name: 'China'},
    {abbr: 'CO', name: 'Colombia'},
    {abbr: 'CR', name: 'Costa Rica'},
    {abbr: 'CU', name: 'Cuba'},
    {abbr: 'CV', name: 'Cape Verde'},
    {abbr: 'CW', name: 'Curaçao'},
    {abbr: 'CX', name: 'Christmas Island'},
    {abbr: 'CY', name: 'Cyprus'},
    {abbr: 'CZ', name: 'Czechia'},
    {abbr: 'DE', name: 'Germany'},
    {abbr: 'DJ', name: 'Djibouti'},
    {abbr: 'DK', name: 'Denmark'},
    {abbr: 'DM', name: 'Dominica'},
    {abbr: 'DO', name: 'Dominican Republic'},
    {abbr: 'DZ', name: 'Algeria'},
    {abbr: 'EC', name: 'Ecuador'},
    {abbr: 'EE', name: 'Estonia'},
    {abbr: 'EG', name: 'Egypt'},
    {abbr: 'EH', name: 'Western Sahara'},
    {abbr: 'ER', name: 'Eritrea'},
    {abbr: 'ES', name: 'Spain'},
    {abbr: 'ET', name: 'Ethiopia'},
    {abbr: 'FI', name: 'Finland'},
    {abbr: 'FJ', name: 'Fiji'},
    {abbr: 'FK', name: 'Falkland Islands'},
    {abbr: 'FO', name: 'Faroe Islands'},
    {abbr: 'FR', name: 'France'},
    {abbr: 'GA', name: 'Gabon'},
    {abbr: 'GB', name: 'United Kingdom'},
    {abbr: 'GD', name: 'Grenada'},
    {abbr: 'GE', name: 'Georgia'},
    {abbr: 'GF', name: 'French Guiana'},
    {abbr: 'GG', name: 'Guernsey'},
    {abbr: 'GH', name: 'Ghana'},
    {abbr: 'GI', name: 'Gibraltar'},
    {abbr: 'GL', name: 'Greenland'},
    {abbr: 'GM', name: 'Gambia'},
    {abbr: 'GN', name: 'Guinea'},
    {abbr: 'GP', name: 'Guadeloupe'},
    {abbr: 'GQ', name: 'Equatorial Guinea'},
    {abbr: 'GR', name: 'Greece'},
    {abbr: 'GS', name: 'South Georgia & South Sandwich Islands'},
    {abbr: 'GT', name: 'Guatemala'},
    {abbr: 'GW', name: 'Guinea-Bissau'},
    {abbr: 'GY', name: 'Guyana'},
    {abbr: 'HK', name: 'Hong Kong SAR China'},
    {abbr: 'HM', name: 'Heard & McDonald Islands'},
    {abbr: 'HN', name: 'Honduras'},
    {abbr: 'HR', name: 'Croatia'},
    {abbr: 'HT', name: 'Haiti'},
    {abbr: 'HU', name: 'Hungary'},
    {abbr: 'ID', name: 'Indonesia'},
    {abbr: 'IE', name: 'Ireland'},
    {abbr: 'IL', name: 'Israel'},
    {abbr: 'IM', name: 'Isle of an'},
    {abbr: 'IN', name: 'India'},
    {abbr: 'IO', name: 'British Indian Ocean Territory'},
    {abbr: 'IQ', name: 'Iraq'},
    {abbr: 'IR', name: 'Iran'},
    {abbr: 'IS', name: 'Iceland'},
    {abbr: 'IT', name: 'Italy'},
    {abbr: 'JE', name: 'Jersey'},
    {abbr: 'JM', name: 'Jamaica'},
    {abbr: 'JO', name: 'Jordan'},
    {abbr: 'JP', name: 'Japan'},
    {abbr: 'KE', name: 'Kenya'},
    {abbr: 'KG', name: 'Kyrgyzstan'},
    {abbr: 'KH', name: 'Cambodia'},
    {abbr: 'KI', name: 'Kiribati'},
    {abbr: 'KM', name: 'Comoros'},
    {abbr: 'KN', name: 'St Kitts & Nevis'},
    {abbr: 'KP', name: 'North Korea'},
    {abbr: 'KR', name: 'South Korea'},
    {abbr: 'KW', name: 'Kuwait'},
    {abbr: 'KY', name: 'Cayman Islands'},
    {abbr: 'KZ', name: 'Kazakhstan'},
    {abbr: 'LA', name: 'Laos'},
    {abbr: 'LB', name: 'Lebanon'},
    {abbr: 'LC', name: 'St Lucia'},
    {abbr: 'LI', name: 'Liechtenstein'},
    {abbr: 'LK', name: 'Sri Lanka'},
    {abbr: 'LR', name: 'Liberia'},
    {abbr: 'LS', name: 'Lesotho'},
    {abbr: 'LT', name: 'Lithuania'},
    {abbr: 'LU', name: 'Luxembourg'},
    {abbr: 'LV', name: 'Latvia'},
    {abbr: 'LY', name: 'Libya'},
    {abbr: 'MA', name: 'Morocco'},
    {abbr: 'MC', name: 'Monaco'},
    {abbr: 'MD', name: 'Moldova'},
    {abbr: 'ME', name: 'Montenegro'},
    {abbr: 'MF', name: 'St Martin'},
    {abbr: 'MG', name: 'Madagascar'},
    {abbr: 'MK', name: 'North Macedonia'},
    {abbr: 'ML', name: 'Mali'},
    {abbr: 'MM', name: 'Myanmar (Burma)'},
    {abbr: 'MN', name: 'Mongolia'},
    {abbr: 'MO', name: 'Macao SAR China'},
    {abbr: 'MQ', name: 'Martinique'},
    {abbr: 'MR', name: 'Mauritania'},
    {abbr: 'MS', name: 'Montserrat'},
    {abbr: 'MT', name: 'Malta'},
    {abbr: 'MU', name: 'Mauritius'},
    {abbr: 'MV', name: 'Maldives'},
    {abbr: 'MW', name: 'Malawi'},
    {abbr: 'MX', name: 'Mexico'},
    {abbr: 'MY', name: 'Malaysia'},
    {abbr: 'MZ', name: 'Mozambique'},
    {abbr: 'NA', name: 'Namibia'},
    {abbr: 'NC', name: 'New Caledonia'},
    {abbr: 'NE', name: 'Niger'},
    {abbr: 'NF', name: 'Norfolk Island'},
    {abbr: 'NG', name: 'Nigeria'},
    {abbr: 'NI', name: 'Nicaragua'},
    {abbr: 'NL', name: 'Netherlands'},
    {abbr: 'NO', name: 'Norway'},
    {abbr: 'NP', name: 'Nepal'},
    {abbr: 'NR', name: 'Nauru'},
    {abbr: 'NU', name: 'Niue'},
    {abbr: 'NZ', name: 'New Zealand'},
    {abbr: 'OM', name: 'Oman'},
    {abbr: 'PA', name: 'Panama'},
    {abbr: 'PE', name: 'Peru'},
    {abbr: 'PF', name: 'French Polynesia'},
    {abbr: 'PG', name: 'Papua New Guinea'},
    {abbr: 'PH', name: 'Philippines'},
    {abbr: 'PK', name: 'Pakistan'},
    {abbr: 'PL', name: 'Poland'},
    {abbr: 'PM', name: 'St Pierre & Miquelon'},
    {abbr: 'PN', name: 'Pitcairn Islands'},
    {abbr: 'PS', name: 'Palestinian Territories'},
    {abbr: 'PT', name: 'Portugal'},
    {abbr: 'PY', name: 'Paraguay'},
    {abbr: 'QA', name: 'Qatar'},
    {abbr: 'RE', name: 'Réunion'},
    {abbr: 'RO', name: 'Romania'},
    {abbr: 'RS', name: 'Serbia'},
    {abbr: 'RU', name: 'Russia'},
    {abbr: 'RW', name: 'Rwanda'},
    {abbr: 'SA', name: 'Saudi Arabia'},
    {abbr: 'SB', name: 'Solomon Islands'},
    {abbr: 'SC', name: 'Seychelles'},
    {abbr: 'SD', name: 'Sudan'},
    {abbr: 'SE', name: 'Sweden'},
    {abbr: 'SG', name: 'Singapore'},
    {abbr: 'SH', name: 'St Helena'},
    {abbr: 'SI', name: 'Slovenia'},
    {abbr: 'SJ', name: 'Svalbard & Jan Mayen'},
    {abbr: 'SK', name: 'Slovakia'},
    {abbr: 'SL', name: 'Sierra Leone'},
    {abbr: 'SM', name: 'San Marino'},
    {abbr: 'SN', name: 'Senegal'},
    {abbr: 'SO', name: 'Somalia'},
    {abbr: 'SR', name: 'Suriname'},
    {abbr: 'SS', name: 'South Sudan'},
    {abbr: 'ST', name: 'São Tomé & Príncipe'},
    {abbr: 'SV', name: 'El Salvador'},
    {abbr: 'SX', name: 'Sint Maarten'},
    {abbr: 'SY', name: 'Syria'},
    {abbr: 'SZ', name: 'Eswatini'},
    {abbr: 'TC', name: 'Turks & Caicos Islands'},
    {abbr: 'TD', name: 'Chad'},
    {abbr: 'TF', name: 'French Southern Territories'},
    {abbr: 'TG', name: 'Togo'},
    {abbr: 'TH', name: 'Thailand'},
    {abbr: 'TJ', name: 'Tajikistan'},
    {abbr: 'TK', name: 'Tokelau'},
    {abbr: 'TL', name: 'Timor-Leste'},
    {abbr: 'TM', name: 'Turkmenistan'},
    {abbr: 'TN', name: 'Tunisia'},
    {abbr: 'TO', name: 'Tonga'},
    {abbr: 'TR', name: 'Turkey'},
    {abbr: 'TT', name: 'Trinidad & Tobago'},
    {abbr: 'TV', name: 'Tuvalu'},
    {abbr: 'TW', name: 'Taiwan'},
    {abbr: 'TZ', name: 'Tanzania'},
    {abbr: 'UA', name: 'Ukraine'},
    {abbr: 'UG', name: 'Uganda'},
    {abbr: 'UM', name: 'U.S. Outlying Islands'},
    {abbr: 'US', name: 'United States'},
    {abbr: 'UY', name: 'Uruguay'},
    {abbr: 'UZ', name: 'Uzbekistan'},
    {abbr: 'VA', name: 'Vatican City'},
    {abbr: 'VC', name: 'St Vincent & Grenadines'},
    {abbr: 'VE', name: 'Venezuela'},
    {abbr: 'VG', name: 'British Virgin Islands'},
    {abbr: 'VN', name: 'Vietnam'},
    {abbr: 'VU', name: 'Vanuatu'},
    {abbr: 'WF', name: 'Wallis & Futuna'},
    {abbr: 'WS', name: 'Samoa'},
    {abbr: 'XK', name: 'Kosovo'},
    {abbr: 'YE', name: 'Yemen'},
    {abbr: 'YT', name: 'Mayotte'},
    {abbr: 'ZA', name: 'South Africa'},
    {abbr: 'ZM', name: 'Zambia'},
    {abbr: 'ZW', name: 'Zimbabwe'},
];